name: Laravel CI

on:
  push:
    branches: ["main", "integration"]
    paths:
      - 'fullstack-blog-backend/**'
  pull_request:
    branches: ["main", "integration"]
    paths:
      - 'fullstack-blog-backend/**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./fullstack-blog-backend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, bcmath, sqlite3, zip, gd, intl

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
      - name: Generate Key
        run: php artisan key:generate

      - name: Execute Tests (PHPUnit)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: php artisan test